### PR TITLE
Typo

### PR DESCRIPTION
**Pull request by sutorinfo**
Standart -> Standard

### CODE REVIEW

**Comment by nuxwin** [comment]
@sutorinfo 

PR on PO (Portable Object) files are not allowed. That is a translation issue so please, register an account on Transifex and fix the issue there.

See https://www.transifex.com/i-mscp/i-MSCP/dashboard/

Thank you for your understanding.

**Comment by theemstra** [comment]
@sutorinfo if you need more help, feel free to contact me

**Comment by sutorinfo** [comment]
@nuxwin @theemstra Thank you all for your patience. I'm not such a core developer. Joined the i-mscp translation team at transifex and added two suggestions. Not enough rights to save. Think, these votes will be sufficient. I think, I can now delete this forked branch.

**Comment by nuxwin** [comment]
@sutorinfo 

You're welcome. @theemstra will take care of you if needed.

**Comment by theemstra** [comment]
All strings that contained "Standart" and "Standard" I unreviewed, so you can take a look at them:
https://www.transifex.com/i-mscp/i-MSCP/translate/#de_DE/1_3_x/83262563?reviewed=no

**Comment by sutorinfo** [comment]
@theemstra Saved them :-) (two items) and completed a third one. Done.

**Comment by theemstra** [comment]
Thanks, I reviewed them for you. They will be synced soon

**Pull request closed without merging**
