### PR TITLE
Added: Second set of listener files

### PR DESCRIPTION
**Pull request by reneschuster**
40_apache2_tools_proxy.pl
50_apache2_hsts.pl
10_nginx_hsts.pl
10_phpfpm_maxchildren.pl
60_postfix_pfs.pl
70_postfix_submission_tls.pl
10_proftpd_tuning.pl
10_roundcube_tls.pl

### CODE REVIEW

**Comment by Ninos** [comment]
If ok I'll remove `50_apache2_hsts.pl`. The HSTS feature is already implemented in 1.3.x. I want to avoids conflicts :-)

**Comment by Ninos** [comment]
For `10_phpfpm_maxchildren.pl` I already created a listener-file, also in 1.3.x branch:
https://github.com/i-MSCP/imscp/blob/1.3.x/contrib/Listeners/PHP-FPM/10_phpfpm_maxchildren.pl

Because of that I may would also remove yours in 1.2.x :D

**Comment by reneschuster** [comment]
Then you could also remove your 10_phpfpm_maxchildren.pl from 1.3.x branch because max_children is now a value in the config in i-MSCP 1.2.12.

https://github.com/i-MSCP/imscp/commit/39f888ad182ece3c01990f836313c76e299fc8ef#diff-ff30083a4464f687dd7074453f6b4367R99

And check also my latest PR: https://github.com/i-MSCP/imscp/pull/56

**Comment by Ninos** [comment]
Ok so I'll remove all 3 listener (your 2 and mine)

**Comment by nuxwin** [comment]
Happy to see that you both follow coming changes ;)

**Pull request merged**
