### PR TITLE
Enable opcode cache for customers

### PR DESCRIPTION
**Pull request by Ninos**
This changes enables the opcode cache for customers again.

See also followin thread:
http://i-mscp.net/index.php/Thread/5055-Error-500-PMA-under-Debian-Jessie/

### CODE REVIEW

**Comment by nuxwin** [comment]
Are you sure this doesn't cause any trouble for Pydio and PMA? Did you tested with both http implementations (PHP5-FPM and Fcgid)? Normally, the processes are separated so this should not cause any problem but I prefer ask before merging.

**Comment by Ninos** [comment]
Sry there was a little problem in my changes. See current version :D

I used now pma and ajaxplorer for 5-10min and all worked fine.

OS: Debian Wheezy x64
PHP: php-fpm 5.5

But maybe there are problems with older php-versions or services.

**Comment by Ninos** [comment]
Little typo. The current version disables the opcache in the master now. But it seems that the current versions of pma and ajaxplorer works now also with php55.

**Comment by nuxwin** [comment]
I'll give a try before merge (I want avoid a disaster again)

**Comment by nuxwin** [comment]
This issue will be addressed in serie 1.2.x

**Pull request closed without merging**
