### PR TITLE
Enhancement: Reseller: Domain expiration date added to overview

### PR DESCRIPTION
**Pull request by theemstra**

### CODE REVIEW

**Comment by nuxwin** [comment]
I'll test and merge in time. Thanks you :)

**Comment by nuxwin** [comment]
A screen please ;)

**Comment by theemstra** [comment]
Hi! Sure: **
I altered my own installation to also have this information in the admin, for testing purposes.
This PR only affects the reseller, which is usually more relevant.

**Comment by nuxwin** [comment]
Re;

Why did not you just not added the missing field instead of deleting the old one?

**Comment by nuxwin** [comment]
Still waiting for answer ;)

**Comment by theemstra** [comment]
In my opinion the 'created' field doesn't add too much, it's there but I wouldn't know what to use it for.
If you want I can change it and add it to this PR

**Comment by nuxwin** [comment]
Yes please, just add your field but don't remove the old one ;)

**Comment by theemstra** [comment]
This will create the extra row

**Comment by nuxwin** [comment]
Thanks ;) Will be merged soon ;)

**Pull request merged**
