### PR TITLE
Added backup mail functionality

### PR DESCRIPTION
**Pull request by admiralmedia**
Added backup mail functionality, so that all the domain mails will have an backup archive.
Added into the reseller control panel adding/editing domains, backups can be set also only to mail. Full backups also backups mails.

### CODE REVIEW

**Comment by nuxwin** [comment]
Thank you ;) I'll review this PR this evening and merge. Will be part of 1.2.3 release ;)

**Comment by nuxwin** [comment]
**Review**
- You added the date in sql dump files but this breaks the restore feature. I understand what you wanted to do here but this is not possible with the current implementation of the backup feature. Doing this would involve too many changes in the engine. Please, revert that part.
- You forgot the hosting plan part: hosting_plan_add.php, hosting_plan_edit.php and the related templates at both admin and reseller levels.

So please, update your PR ;)

Will be now part of version 1.2.4 if ready

Thanks

**Comment by admiralmedia** [comment]
Hi,

I've added also the hosting add/edit commits and removed the date/time from sql backup.

**Comment by Ninos** [comment]
Merged in new branch:
https://github.com/i-MSCP/imscp/tree/feature-backup

I'll review and then merge into 1.2.x branch. Thanks for your PR!

**Pull request closed without merging**
