### PR TITLE
Updated: Add Referrer-Policy header to 40_apache2_security_headers.pl…

### PR DESCRIPTION
**Pull request by reneschuster**
… listener file

### CODE REVIEW

**Comment by nuxwin** [comment]
@reneschuster 

Since those headers are added in all vhosts, I'm wondering if this would not be more practical to add them once in the https://github.com/i-MSCP/imscp/blob/1.4.x/configs/debian/apache/00_nameserver.conf#L59 file. We could add them during setup phase ;) What do you think about this?

**Comment by reneschuster** [comment]
@nuxwin 

Normally I would agree, but today I was thinking if it would make sense to extend the script by the option to define individual headers by domain names.

**Comment by nuxwin** [comment]
@reneschuster 

I'm fine with the idea to be able to enable those headers on a per domain basis ;)

**Comment by reneschuster** [comment]
@nuxwin 

Ok, then I'll change the listener file to support both, global options or on a per domain basis.

**Pull request merged**
